name: test

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install .[dev]

    # required only if you want to verify C# with SourceExpander
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Install dependencies (C#)
      run: dotnet tool install -g SourceExpander.Console

    - name: Run tests
      run: |
        unset GITHUB_ACTION
        oj-verify -h
        python setup.py test
      shell: bash
